### ISSUE TITLE
Groups Within Default

### ISSUE THREAD

**Issue by MacSplody** [loot/fallout4#100]
So the main idea would be to create new groups within default.
This would avoid moving mods too quickly from their default sorting position.
It would also allow unknown mods (i.e mods not in the master list) within the default group to still sort within these new groups.
Below is an example group layout.
![image](https://user-images.githubusercontent.com/1944639/53603991-1a684c00-3bab-11e9-94c4-69445f5cc5ad.png)

Custom Rules used
```yaml
groups:
  - name: 'Animations'
    after:
      - Core
  - name: 'NPC & Faction Overhauls'
    after:
      - Character Appearance Resources
      - Armor & Apparel
  - name: 'Scrap Everything'
    after:
      - NPC & Faction Overhauls
  - name: 'Character Appearance Resources'
    after:
      - Animations
  - name: 'Armor & Apparel'
    after:
      - Weapons & Gadgets
  - name: 'Core'
    after:
      - Scrap Corpse Highlighting
  - name: 'default'
  - name: 'User interface'
    after:
      - Core
  - name: 'Weapons & Gadgets'
    after:
      - User interface
plugins:
  - name: '3dscopes.esp'
    group: 'Weapons & Gadgets'
  - name: 'ABundleofTape.esp'
    group: 'Weapons & Gadgets'
  - name: 'AKM_AKMS.esp'
    group: 'Weapons & Gadgets'
  - name: 'Archimedes-II.esp'
    group: 'Weapons & Gadgets'
  - name: 'Armorsmith Extended.esp'
    group: 'Armor & Apparel'
  - name: 'AzarPonytailHairstyles.esp'
    group: 'Character Appearance Resources'
  - name: 'Backpacks of the Commonwealth.esp'
    group: 'Armor & Apparel'
  - name: 'BerettaM9FS.esp'
    group: 'Weapons & Gadgets'
  - name: 'Binoculars.esp'
    group: 'Weapons & Gadgets'
  - name: 'CBBE.esp'
    group: 'Character Appearance Resources'
  - name: 'ChiappaTripleThreat.esp'
    group: 'Weapons & Gadgets'
  - name: 'CROSS_Blades.esp'
    group: 'Weapons & Gadgets'
  - name: 'CROSS_BreakActionLaser.esp'
    group: 'Weapons & Gadgets'
  - name: 'CROSS_BrotherhoodRecon.esp'
    group: 'Armor & Apparel'
  - name: 'CROSS_CourserStrigidae.esp'
    group: 'Armor & Apparel'
  - name: 'CROSS_CryoLance.esp'
    group: 'Weapons & Gadgets'
  - name: 'CROSS_Cybernetics.esp'
    group: 'Armor & Apparel'
  - name: 'CROSS_InstituteExpeditionarySuit.esp'
    group: 'Armor & Apparel'
  - name: 'Crossbow.esp'
    group: 'Weapons & Gadgets'
  - name: 'D.E.C.A.Y.esp'
    group: 'NPC & Faction Overhauls'
  - name: 'DeadlierDeathclaws.esp'
    group: 'NPC & Faction Overhauls'
  - name: 'EAMR.esp'
    group: 'Armor & Apparel'
  - name: 'Edit_Hancock.esp'
    group: 'NPC & Faction Overhauls'
  - name: 'EnclaveX02.esp'
    group: 'Armor & Apparel'
  - name: 'Enhanced Commonwealth Wardrobe.esp'
    group: 'Armor & Apparel'
  - name: 'FALLOUT4WT.esp'
    group: 'Armor & Apparel'
  - name: 'FO4Hotkeys.esp'
    group: 'User interface'
  - name: 'FOFW_ALL_IN_ONE_VANILLA.esp'
    group: 'NPC & Faction Overhauls'
  - name: 'Friffy_Holstered Weapons.esp'
    group: 'Weapons & Gadgets'
  - name: 'G11.esp'
    group: 'Weapons & Gadgets'
  - name: 'Hellfirenew.esp'
    group: 'Armor & Apparel'
  - name: 'Immersive Fallout - Movement (DLC).esp'
    group: 'Animations'
  - name: 'Immersive Fallout - Real Recoil (DLC).esp'
    group: 'Animations'
  - name: 'Immersive Fallout - Realistic ADS (DLC).esp'
    group: 'Animations'
  - name: 'Immersive HUD.esp'
    group: 'User interface'
  - name: 'Improved Jetpack Flight Model.esp'
    group: 'Core'
  - name: 'Live Action Handy.esp'
    group: 'NPC & Faction Overhauls'
  - name: 'LMBTOverlays.esp'
    group: 'Character Appearance Resources'
  - name: 'LooksMenu Customization Compendium.esp'
    group: 'Character Appearance Resources'
  - name: 'LooksMenu.esp'
    group: 'Character Appearance Resources'
  - name: 'LoreFriendlySurvivalChems.esp'
    group: 'Core'
  - name: 'LOST Tweaks & Enhancements.esp'
    group: 'Core'
  - name: 'M2045MagnumRevolverRifle.esp'
    group: 'Weapons & Gadgets'
  - name: 'Mercenary.esp'
    group: 'Armor & Apparel'
  - name: 'MercenaryCBBEPatch_NoAE.esp'
    group: 'Armor & Apparel'
  - name: 'PA-Quick Animations.esp'
    group: 'Animations'
  - name: 'PD_LowerWeapon.esp'
    group: 'Animations'
  - name: 'QuickTrade.esp'
    group: 'User interface'
  - name: 'RAW INPUT.esp'
    group: 'Animations'
  - name: 'Realistic Death Physics.esp'
    group: 'Animations'
  - name: 'Realistic_conversations.esp'
    group: 'Core'
  - name: 'RemoteExplosives.esp'
    group: 'Weapons & Gadgets'
  - name: 'RingsTogether.esp'
    group: 'Armor & Apparel'
  - name: 'SanctuaryNPCsOverhaul.esp'
    group: 'NPC & Faction Overhauls'
  - name: 'SettlementMenuManager.esp'
    group: 'Core'
  - name: 'spacefiddle_Follower-Stealth-Distance-Fixes.esp'
    group: 'Core'
  - name: 'SuperMutantRedux.esp'
    group: 'NPC & Faction Overhauls'
  - name: 'Swinging Meat Bags.esp'
    group: 'Animations'
  - name: 'Synth Overhaul.esp'
    group: 'NPC & Faction Overhauls'
  - name: 'Tactical Flashlights - Settings.esp'
    group: 'Armor & Apparel'
  - name: 'Tactical Flashlights.esp'
    group: 'Armor & Apparel'
  - name: 'Targeting Sensors on Recon Scopes.esp'
    group: 'Core'
  - name: 'The Eyes Of Beauty.esp'
    group: 'Character Appearance Resources'
  - name: 'TheKite_Railroad_Handmaiden.esp'
    group: 'Armor & Apparel'
  - name: 'Tomacuzi9.esp'
    group: 'Weapons & Gadgets'
  - name: 'Unique NPCs - Creatures and Monsters.esp'
    group: 'NPC & Faction Overhauls'
  - name: 'Unique NPCs.esp'
    group: 'NPC & Faction Overhauls'
  - name: 'VIS-G Item Sorting Vanilla Weight Patch.esp'
    group: 'User interface'
  - name: 'VIS-G Item Sorting.esp'
    group: 'User interface'
  - name: 'VisibleCompanionAffinity.esp'
    group: 'User interface'
  - name: 'VisibleWeapons.esp'
    group: 'Weapons & Gadgets'
  - name: 'WastelandCodex.esp'
    group: 'User interface'
  - name: 'WattzLaserGun.esp'
    group: 'Weapons & Gadgets'
  - name: 'Yagisan_WO_Better_Caravans.esp'
    group: 'NPC & Faction Overhauls'
```

Load Order produced
```
  0  0     Fallout4.esm
  1  1     DLCRobot.esm
  2  2     DLCworkshop01.esm
  3  3     DLCCoast.esm
  4  4     DLCworkshop02.esm
  5  5     DLCworkshop03.esm
  6  6     DLCNukaWorld.esm
  7  7     Unofficial Fallout 4 Patch.esp
  8  8     ArmorKeywords.esm
  9  9     HUDFramework.esm
 10  a     XDI.esm
 11  b     SettlementMenuManager.esp
254 FE   0 Targeting Sensors on Recon Scopes.esp
254 FE   1 spacefiddle_Follower-Stealth-Distance-Fixes.esp
254 FE   2 Improved Jetpack Flight Model.esp
 12  c     Realistic_conversations.esp
254 FE   3 LOST Tweaks & Enhancements.esp
254 FE   4 LoreFriendlySurvivalChems.esp
 13  d     FO4Hotkeys.esp
 14  e     Immersive HUD.esp
 15  f     VisibleCompanionAffinity.esp
 16 10     QuickTrade.esp
 17 11     WastelandCodex.esp
 18 12     Realistic Death Physics.esp
 19 13     Immersive Fallout - Movement (DLC).esp
 20 14     RAW INPUT.esp
 21 15     Immersive Fallout - Real Recoil (DLC).esp
 22 16     PD_LowerWeapon.esp
 23 17     PA-Quick Animations.esp
 24 18     Swinging Meat Bags.esp
 25 19     Immersive Fallout - Realistic ADS (DLC).esp
 26 1a     LooksMenu.esp
 27 1b     LMBTOverlays.esp
 28 1c     AzarPonytailHairstyles.esp
 29 1d     The Eyes Of Beauty.esp
254 FE   5 VIS-G Item Sorting.esp
254 FE   6 VIS-G Item Sorting Vanilla Weight Patch.esp
 30 1e     Archimedes-II.esp
254 FE   7 CROSS_CryoLance.esp
254 FE   8 CROSS_Blades.esp
 31 1f     AKM_AKMS.esp
 32 20     ChiappaTripleThreat.esp
 33 21     Crossbow.esp
 34 22     ABundleofTape.esp
 35 23     Tomacuzi9.esp
 36 24     G11.esp
 37 25     WattzLaserGun.esp
 38 26     M2045MagnumRevolverRifle.esp
 39 27     BerettaM9FS.esp
254 FE   9 CROSS_BreakActionLaser.esp
 40 28     RemoteExplosives.esp
 41 29     3dscopes.esp
 42 2a     Binoculars.esp
 43 2b     VisibleWeapons.esp
 44 2c     Friffy_Holstered Weapons.esp
 45 2d     Armorsmith Extended.esp
 46 2e     EAMR.esp
 47 2f     Backpacks of the Commonwealth.esp
 48 30     Enhanced Commonwealth Wardrobe.esp
 49 31     Mercenary.esp
 50 32     RingsTogether.esp
 51 33     CROSS_Cybernetics.esp
 52 34     MercenaryCBBEPatch_NoAE.esp
254 FE   a CROSS_BrotherhoodRecon.esp
254 FE   b CROSS_InstituteExpeditionarySuit.esp
254 FE   c CROSS_CourserStrigidae.esp
254 FE   d TheKite_Railroad_Handmaiden.esp
 53 35     Tactical Flashlights.esp
 54 36     EnclaveX02.esp
 55 37     Hellfirenew.esp
 56 38     CBBE.esp
 57 39     Tactical Flashlights - Settings.esp
 58 3a     FALLOUT4WT.esp
 59 3b     Unique NPCs.esp
 60 3c     LooksMenu Customization Compendium.esp
 61 3d     Unique NPCs - Creatures and Monsters.esp
 62 3e     FOFW_ALL_IN_ONE_VANILLA.esp
 63 3f     SuperMutantRedux.esp
 64 40     DeadlierDeathclaws.esp
 65 41     Live Action Handy.esp
 66 42     Edit_Hancock.esp
 67 43     SanctuaryNPCsOverhaul.esp
254 FE   e Yagisan_WO_Better_Caravans.esp
 68 44     D.E.C.A.Y.esp
 69 45     Synth Overhaul.esp
254 FE   f UDO4P_CR_Patch.esp
```
