### ISSUE TITLE
The Machine And Her - Cleaning Info

### ISSUE THREAD

**Issue by MacSplody** [loot/fallout4#123]
[The Machine And Her](https://www.nexusmods.com/fallout4/mods/30488)
version: 0.7

```yaml
  - name: 'AGNISNikaCola01.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0x76B29A1E
        util: '[FO4Edit v4.0.2i](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 7
        nav: 10
      # version: 0.7, after QAC
      - <<: *reqManualFix
        crc: 0x9819516A
        util: '[FO4Edit v4.0.2i](https://www.nexusmods.com/fallout4/mods/2737)'
        nav: 10
```
