### ISSUE TITLE
The Bleachers - Cleaning Info

### ISSUE THREAD

**Issue by MacSplody** [loot/fallout4#124]
[The Bleachers - A Diamond City Story](https://www.nexusmods.com/fallout4/mods/40267)
version: 0.941

```yaml
  - name: 'DCGuard_Overhaul.esp'
    dirty:
      - <<: *quickClean
        crc: 0xFF309CF6
        util: '[FO4Edit v4.0.2i](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 2
```
