### ISSUE TITLE
Combat Zone Restored - Cleaning Info

### ISSUE THREAD

**Issue by MacSplody** [loot/fallout4#125]
[Combat Zone Restored](https://www.nexusmods.com/fallout4/mods/21498)
version: 1.02
```yaml
  - name: 'CombatZoneRestored.esp'
    dirty:
      - <<: *reqManualFix
        crc: 0x74BE02DE
        util: '[FO4Edit v4.0.2i](https://www.nexusmods.com/fallout4/mods/2737)'
        nav: 1
```

**Comment by ghost** [comment]
Already solved.

See line 3711, reading exactly as:
```
   - name: 'CombatZoneRestored.esp'
    url: [ 'https://www.nexusmods.com/fallout4/mods/21498' ]
    dirty:
      # 1.02
      - <<: *reqManualFix
        crc: 0x74BE02DE
        util: '[FO4Edit v4.0.2f](https://www.nexusmods.com/fallout4/mods/2737)'
        nav: 1
```
