### ISSUE TITLE
Mechanist's Lair expanded - Cleaning Info

### ISSUE THREAD

**Issue by MacSplody** [loot/fallout4#134]
[Mechanist's Lair - expanded corrected and fixed](https://www.nexusmods.com/fallout4/mods/11490)
Version: 0.1

```yaml
  - name: 'MechanistsLair_fix_only.esp'
    dirty:
      - <<: *quickClean
        crc: 0xEF7399E0
        util: '[FO4Edit v4.0.2j](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 13
  - name: 'MechanistsLair_V1.esp'
    dirty:
      - <<: *quickClean
        crc: 0x1E42B3E3
        util: '[FO4Edit v4.0.2j](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 11
  - name: 'MechanistsLair_V2.esp'
    dirty:
      - <<: *quickClean
        crc: 0x7DD23517
        util: '[FO4Edit v4.0.2j](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 11
  - name: 'MechanistsLair_V3.esp'
    dirty:
      - <<: *quickClean
        crc: 0x7DBD6DA2
        util: '[FO4Edit v4.0.2j](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 11
  - name: 'MechanistsLair_V4.esp'
    dirty:
      - <<: *quickClean
        crc: 0x2DFE73AE
        util: '[FO4Edit v4.0.2j](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 11
```
