### ISSUE TITLE
CC Cleaning Info

### ISSUE THREAD

**Issue by MacSplody** [loot/fallout4#135]
```yaml
  - name: 'ccbgsfo4117-capmerc.esl'
    dirty:
      - <<: *quickClean
        crc: 0x67206ED6
        util: '[FO4Edit v4.0.3](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 33
    clean:
      - crc: 0x912D89A7
        util: 'FO4Edit v4.0.3'

  - name: 'ccgcafo4025-pagunmm.esl'
    dirty:
      - <<: *quickClean
        crc: 0x88799C6D
        util: '[FO4Edit v4.0.3](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 3
    clean:
      - crc: 0x98B17D05
        util: 'FO4Edit v4.0.3'

  - name: 'ccbgsfo4046-tescan.esl'
    dirty:
      - <<: *quickClean
        crc: 0xF67EB2BF
        util: '[FO4Edit v4.0.3](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 10
    clean:
      - crc: 0xDF5F6EBD
        util: 'FO4Edit v4.0.3'

  - name: 'ccfsvfo4006-vrwasteland.esl'
    dirty:
      - <<: *quickClean
        crc: 0xB30F7A1D
        util: '[FO4Edit v4.0.3](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 111
    clean:
      - crc: 0xDB3401F9
        util: 'FO4Edit v4.0.3'

  - name: 'ccfsvfo4004-vrworkshopgnrplaza.esl'
    dirty:
      - <<: *quickClean
        crc: 0xAC9CD310
        util: '[FO4Edit v4.0.3](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 8
    clean:
      - crc: 0xB0263C72
        util: 'FO4Edit v4.0.3'

  - name: 'ccfsvfo4005-vrdesertisland.esl'
    dirty:
      - <<: *quickClean
        crc: 0xAA9EBB60
        util: '[FO4Edit v4.0.3](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 92
    clean:
      - crc: 0x9889CA15
        util: 'FO4Edit v4.0.3'

  - name: 'ccbgsfo4040-vrworkshop01.esl'
    dirty:
      - <<: *quickClean
        crc: 0x64F72538
        util: '[FO4Edit v4.0.3](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 3
    clean:
      - crc: 0xE9C45B08
        util: 'FO4Edit v4.0.3'
```
