### ISSUE TITLE
Unlimited Companion Framework should load after Everyone's Best Friend

### ISSUE THREAD

**Issue by lavacano** [loot/fallout4#140]
#### [Everyone's Best Friend (Dogmeat and Companion At Same Time - No Console - No Hack)](https://www.nexusmods.com/fallout4/mods/13459)

UFF/EFF.esp loads a ba2 with $data/scripts/followersscript.pex it must not be overwritten.  

```yaml
  - name: 'EFF.esp'
    after:
      - 'EveryonesBestFriend.esp'
```
