### ISSUE TITLE
"Better Locational Damage" and "Weaponsmith Extended 2"

### ISSUE THREAD

**Issue by lavacano** [loot/fallout4#141]
### [Weaponsmith Extended](https://www.nexusmods.com/fallout4/mods/10737)

on the downlad page for WSE2 >Optional Files > WSE2 - BLD Patch the nomenclature is as follows:

> This is a patch when using Better Locational Damage.
> -Adds WSE calibers to the headshot list where applicable
> -Adds WSE Melee weapons to appropriate lists
> -merged DLC+Ghoul+VATS+VIS tags
> 
> Req:
> AWKCR
> Better Perks (from BLD)
> Better Locational Damage
> WSE2

Whats funny is that is how the load order should be!

```
  - name: 'Better Perks.esp'
    after:
      - 'ArmorKeywords.esm'
  - name: 'Better Locational Damage.esp'
    after:
      - 'Better Perks.esp'
  - name: 'Weaponsmith Extended 2.esp'
    after:
      - 'Better Locational Damage.esp'
  - name: 'BLD - Merged - WSE Edition.esp'
    after:
      - 'Weaponsmith Extended 2.esp'
```

**Comment by MacSplody** [comment]
```yaml
  - name: 'Better Perks.esp'
    after:
      - 'ArmorKeywords.esm'
```

`ArmorKeywords.esm` is an ESM so it will already sort before `Better Perks.esp`.


`Better Perks.esp` before `Better Locational Damage.esp`
The order doesn't matter as there are no direct conflicts between the two plugins.

`Better Perks.esp` before `Weaponsmith Extended 2.esp`.
The conflicts are resolved by the patch so again the order doesn't matter.
If no patch was used, I'd expect `Better Perks.esp` to be after `Weaponsmith Extended 2.esp` since it's a much smaller mod.

`Weaponsmith Extended 2.esp` will need an after for `Better Locational Damage.esp`.

The Better Locational Damage plugins that are listed as merged into the `BLD - Merged - WSE Edition.esp` patch. 

![image](https://user-images.githubusercontent.com/1944639/74742881-53378000-5257-11ea-9eac-cf7109840171.png)

- `Better Locational Damage - DLC_Automatron.esp`
- `Better Locational Damage - DLC_Far_Harbor.esp`
- `Better Locational Damage - DLC_Nuka_World.esp`
- `Better Locational Damage - DLC_WWorkshop.esp`
- `Better Locational Damage - Ghoul Edition.esp`
- `Better VATS - 0.75.esp`

Some of the DLC plugin changes are not included in the merge.
I'd assume for keeping in line with `Weaponsmith Extended 2.esp`.

---

- [x] Sort `Weaponsmith Extended 2.esp` after `Better Locational Damage.esp`.
- [x] Add already included in `BLD - Merged - WSE Edition.esp` patch` messages.
