### ISSUE TITLE
Institute Patch for PRC

### ISSUE THREAD

**Issue by MacSplody** [loot/fallout4#168]
[PRC - PhotoRealistic Commonwealth](https://www.nexusmods.com/fallout4/mods/6796)

![image](https://user-images.githubusercontent.com/1944639/81945634-44622e80-95f6-11ea-9dfe-fce65f089dc9.png)

> Load after ELFX, NAT, ENB Lights Overhaul & Fr4nsson's Light Tweaks

Version 0.1
```yaml
  - name: 'Institute Patch for PRC.esp'
    dirty:
      - <<: *quickClean
        crc: 0xBA16C65A
        util: '[FO4Edit v4.0.3](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 5
        udr: 40
```

- [x] Add cleaning info.
- [x] Add ~afters.~ group assigment.
