### ISSUE TITLE
Faction Housing Overhaul - All In One

### ISSUE THREAD

**Issue by sibir-ine** [loot/fallout4#257]
[Link](https://www.nexusmods.com/fallout4/mods/15814/)

It was [reported](https://discord.com/channels/473542112974077963/473542230095822848/829631187223838740) in Discord & throughout the mod's page that loading this mod too early causes issues.

<img width="885" height="452" alt="Image" src="https://github.com/user-attachments/assets/a4d4d59a-6bbc-48c9-bc98-0a77a0daee62" />

I'm assuming that's caused by other mods editing the same cells loading after & reverting XPRI entries.

![image](https://user-images.githubusercontent.com/69141501/113998620-16896800-980e-11eb-81c5-78caffd1b67d.png)

Maybe it'd be worth adding a late-loading group for mods that depend on these edits being preserved. However, I have little experience with FO4 modding, so I don't know if this is common behavior & can only be realistically handled on a case-by-case basis with `after`s.

If not, there's still metadata worth creating an entry for (minus the comments of course).

```yaml
  - name: 'Eli_Faction Housing Overhaul - AiO.esp'
    url: [ 'https://www.nexusmods.com/fallout4/mods/15814/' ]
    # 842B406B is vanilla pre-cleaning, 2E1C382E is vanilla post-cleaning (same for 4.0.3 & 4.0.3f)
    msg:
      - <<: *useVersionFarHarbor
        condition: 'active("DLCCoast.esm") and (checksum("Eli_Faction Housing Overhaul - AiO.esp", 842B406B) or checksum("Eli_Faction Housing Overhaul - AiO.esp", 2E1C382E))'
    dirty:
      # v1.2 Vanilla
      - <<: *quickClean
        crc: 0x842B406B
        util: '[FO4Edit v4.0.3f](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 122
      # v1.2 Far Harbor
      - <<: *quickClean
        crc: 0x9F6AA351
        util: '[FO4Edit v4.0.3f](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 127
```
