### ISSUE TITLE
Flirty Commonwealth - Move to early group

### ISSUE THREAD

**Issue by MacSplody** [loot/fallout4#309]
### [Flirty Commonwealth](https://www.nexusmods.com/fallout4/mods/26638/)

It's sorted later than most files by LOOT due to its size.
It reverts changes in a lot of other files, and also distorts the sorting algorithm.

```yaml
  - name: 'IcebreakerCDO-Piper.esp'
    after:
      - 'FlirtyCommonwealthFemale.esp'
      - 'FlirtyCommonwealthMale.esp'
  - name: 'ImmersiveGenericDialogues.esp'
    after:
      - 'FlirtyCommonwealth.esp'
      - 'FlirtyCommonwealthMale.esp'
      - 'FlirtyCommonwealthMM.esp'
      - 'FlirtyCommonwealthFemale.esp'
  - name: 'PiperCaitCurieDialogueOverhaul.esp'
    after:
      - 'FlirtyCommonwealth.esp'
      - 'ImmersiveGenericDialogues.esp'
      - 'FlirtyCommonwealthMale.esp'
      - 'FlirtyCommonwealthMM.esp'
      - 'FlirtyCommonwealthFemale.esp'
  - name: 'PlayerComments.esp'
    after:
      - 'FlirtyCommonwealth.esp'
      - 'FlirtyCommonwealthFemale.esp'
      - 'FlirtyCommonwealthMale.esp'
      - 'FlirtyCommonwealthMM.esp'
```

[No Companion Junk Comments](https://www.nexusmods.com/fallout4/mods/10365/)

No direct conflicts that matter, but the load after rules are required.
To prevent `No Junk Comments.esp` being sorted incorrectly.

`No Junk Comments.esp` correctly sorts after `PiperCaitCurieDialogueOverhaul.esp` with default sorting.
If `PiperCaitCurieDialogueOverhaul.esp` is set to load after `FlirtyCommonwealth.esp`.
`No Junk Comments.esp` willl then be placed before `PiperCaitCurieDialogueOverhaul.esp`.
These load after rules are then required to correct the sorting.

```yaml
  - name: 'No Junk Comments.esp'
    after:
      - 'FlirtyCommonwealth.esp'
      - 'FlirtyCommonwealthMale.esp'
      - 'FlirtyCommonwealthMM.esp'
      - 'FlirtyCommonwealthFemale.esp'
```

---

> . If you're using Set me Up or any alternate start mod. Please load their plugin AFTER this mod's plugin. 

No conflicts with any version.

![image](https://user-images.githubusercontent.com/1944639/138030821-19584dbf-bbf2-437f-9444-b2321a96bcac.png)

> If you're using Better The Third Rail and Better Goodneighbor. Please load their plugin BEFORE this mod's plugin.  

No conflict with either file.

![image](https://user-images.githubusercontent.com/1944639/138029135-b235be57-0f88-48fa-8fac-e0ef86eb394b.png)
