### ISSUE TITLE
Wasteland Imports

### ISSUE THREAD

**Issue by MacSplody** [loot/fallout4#366]
### [Wasteland Imports - Goodies from all across the Wasteland...](https://www.nexusmods.com/fallout4/mods/3793/)

Requires tags for leveled list changes, Delev & Relev.

Cleaning data:
Version 1.52
```yaml
  - name: 'MojaveImports.esp'
    clean:
      - crc: 0x2DCA71E4
        util: 'FO4Edit v4.0.3h (Hotfix 1)'
```
Version 1.52.1
```yaml
  - name: 'MojaveImports.esp'
    clean:
      - crc: 0x58BF06AA
        util: 'FO4Edit v4.0.3h (Hotfix 1)'
```

- [x] Add Tag suggestions,
- [x] Add cleaning data.
