### ISSUE TITLE
Update Previsibines Repair Pack. Again.

### ISSUE THREAD

**Issue by Diskmaster** [loot/fallout4#425]
https://www.nexusmods.com/fallout4/mods/35720 (Flicker Fixer) recently changed to be a Modder's Resource. I've spoken to Glass in another discord and the mod has basically been included with builds starting from 0.57 ~~(the build currently cooking on my PC as I speak).~~

This is just a heads up about it. ~~I'll send along updated cleaning data when I have it, as I need to rebuild all the patches and possibly move them to separate mod pages.~~

**Comment by sibir-ine** [comment]
Okay, so a message like the following would be appropriate?

```yaml
  - name: 'Flicker Fixer.esp'
    msg:
      - <<: *alreadyInOrFixedByX
        subs: [ 'Previsibines Repair Pack v0.57+' ]
        condition: 'version("PRP.esp", "0.57", >=)'
```

`alreadyInOrFixedByX` is as follows:

```yaml
    - &alreadyInOrFixedByX
      type: error
      content: 'Delete. Already included or otherwise fixed in %1%.'
```

**Comment by Diskmaster** [comment]
That will work perfectly, though the plugin is versioned 0.57 in both PRP.esp and PPF.esm (the esm is new, but they both have the same version).

**Comment by sibir-ine** [comment]
Got it. It'd evaluate the same, but it's better to be consistent with how the version is reported in the plugin.

**Comment by Diskmaster** [comment]
I adopted the simpler major.minor.revision approach to versioning, so that should definitely suffice. Thanks as always. ~~Remind me to get you guys cleaning data once I finish updating the compat grabbag.~~

**Comment by Diskmaster** [comment]
English version.

```yaml
# 0.57.1 - Main
  - name: 'PPF.esm'
    clean:
      - crc: 0xAC560B59
        util: 'FO4Edit v4.0.4b'
  - name: 'PRP.esp'
    clean:
      - crc: 0x71362203
        util: 'FO4Edit v4.0.4b'
# 0.57.1a - Compat Grabbag
  - name: 'PRP-Compat-Clarity-42.esp'
    clean:
      - crc: 0x0E13C44E
        util: 'FO4Edit v4.0.4b'
  - name: 'PRP-Compat-Clarity-43.esp'
    clean:
      - crc: 0x0E13C44E
        util: 'FO4Edit v4.0.4b'
  - name: 'PRP-Compat-DCA.esp'
    clean:
      - crc: 0x6CFCCB9D
        util: 'FO4Edit v4.0.4b'
  - name: 'PRP-Compat-Fogout-Int.esp'
    clean:
      - crc: 0x444F032D
        util: 'FO4Edit v4.0.4b'
  - name: 'PRP-Compat-IntEnh.esp'
    clean:
      - crc: 0x3242EBDB
        util: 'FO4Edit v4.0.4b'
  - name: 'PRP-Compat-RegionNames.esp'
    clean:
      - crc: 0x37BC2B72
        util: 'FO4Edit v4.0.4b'
  - name: 'PRP-Compat-UIL.esp'
    clean:
      - crc: 0xF7BEF984
        util: 'FO4Edit v4.0.4b'
  - name: 'PRP-Compat-UIL-Darker.esp'
    clean:
      - crc: 0x55F76C29
        util: 'FO4Edit v4.0.4b'
# 0.57-hotfixL - SS2 patch
  - name: 'PRP-SS2.esp'
    clean:
      - crc: 0xE2FF957B
        util: 'FO4Edit v4.0.4b'
```
