### ISSUE TITLE
PRP 0.59.4 Cleaning Data

### ISSUE THREAD

**Issue by Diskmaster** [loot/fallout4#454]
0.59.4 - Opted to file a bug due to the size of the cleaning data.

```yaml
  - name: 'PPF.esm'
    clean:
      # EN
      - crc: 0x1CEB3329
        util: 'FO4Edit v4.0.4b'
      # ES
      - crc: 0x07F1184F
        util: 'FO4Edit v4.0.4b'
      # IT
      - crc: 0xF2CC63E1
        util: 'FO4Edit v4.0.4b'
  - name: 'PRP.esp'
    clean:
      # EN
      - crc: 0x0FD12B68
        util: 'FO4Edit v4.0.4b'
      # ES
      - crc: 0x21A97BD2
        util: 'FO4Edit v4.0.4b'
      # IT
      - crc: 0xE0490212
        util: 'FO4Edit v4.0.4b'
  - name: 'PRP-Compat-Clarity-42.esp'
    clean:
      # EN
      - crc: 0x94691987
        util: 'FO4Edit v4.0.4b'
      # ES
      - crc: 0x90482194
        util: 'FO4Edit v4.0.4b'
      # IT
      - crc: 0xE51D9C25
        util: 'FO4Edit v4.0.4b'
  - name: 'PRP-Compat-Clarity-43.esp'
    clean:
      # EN
      - crc: 0x94691987
        util: 'FO4Edit v4.0.4b'
      # ES
      - crc: 0x90482194
        util: 'FO4Edit v4.0.4b'
      # IT
      - crc: 0xE51D9C25
        util: 'FO4Edit v4.0.4b'
  - name: 'PRP-Compat-DCA.esp'
    clean:
      # EN
      - crc: 0xF9AD0032
        util: 'FO4Edit v4.0.4b'
      # ES
      - crc: 0xDFE299C5
        util: 'FO4Edit v4.0.4b'
      # IT
      - crc: 0x27625A9E
        util: 'FO4Edit v4.0.4b'
  - name: 'PRP-Compat-Fogout-Int.esp'
    clean:
      # EN
      - crc: 0x284EEEA1
        util: 'FO4Edit v4.0.4b'
      # ES
      - crc: 0x3D258C9C
        util: 'FO4Edit v4.0.4b'
      # IT
      - crc: 0xF63F0472
        util: 'FO4Edit v4.0.4b'
  - name: 'PRP-Compat-IntEnh.esp'
    clean:
      # EN
      - crc: 0x382403E5
        util: 'FO4Edit v4.0.4b'
      # ES
      - crc: 0x45666327
        util: 'FO4Edit v4.0.4b'
      # IT
      - crc: 0xA9B68F2C
        util: 'FO4Edit v4.0.4b'
  - name: 'PRP-Compat-UEL.esp'
    clean:
      # EN
      - crc: 0x4167AC1D
        util: 'FO4Edit v4.0.4b'
      # ES
      - crc: 0xCAC93BC6
        util: 'FO4Edit v4.0.4b'
      # IT
      - crc: 0x88EFD7AD
        util: 'FO4Edit v4.0.4b'
  - name: 'PRP-Compat-UIL-Darker.esp'
    clean:
      # EN
      - crc: 0xE0D9E2D8
        util: 'FO4Edit v4.0.4b'
      # ES
      - crc: 0x50A9B2CE
        util: 'FO4Edit v4.0.4b'
      # IT
      - crc: 0xE1EC93E4
        util: 'FO4Edit v4.0.4b'
  - name: 'PRP-Compat-UIL.esp'
    clean:
      # EN
      - crc: 0xE19391A7
        util: 'FO4Edit v4.0.4b'
      # ES
      - crc: 0x3D8703F1
        util: 'FO4Edit v4.0.4b'
      # IT
      - crc: 0x9C3664C5
        util: 'FO4Edit v4.0.4b'
  - name: 'PRP-Compat-RegionNames.esp'
    clean:
      # EN
      - crc: 0xE46BCAC5
        util: 'FO4Edit v4.0.4b'
      # ES
      - crc: 0x8DC45E56
        util: 'FO4Edit v4.0.4b'
      # IT
      - crc: 0xC82D5E8A
        util: 'FO4Edit v4.0.4b'
```
