### ISSUE TITLE
Yet another PRP related update.

### ISSUE THREAD

**Issue by Diskmaster** [loot/fallout4#464]
https://www.nexusmods.com/fallout4/mods/60330 for the second and third entries.
```
# Should already be autosorted correctly. Not sure how I want to handle other plugins compat against this, might have to rebuild the simpler mods with the partial flag.
  - name: 'PRP-Compat-PointLookout.esp'
    clean:
      - crc: 0x8963D59A
        util: 'FO4Edit v4.0.4b'
# Main Point Lookout esm
  - name: 'CWPointLookoutFO4.esm'
    dirty:
      - <<: *quickClean
        crc: 0x0E34764D
        util: '[FO4Edit v4.0.4b](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 78
    clean:
      - crc: 0xDF00D280
        util: 'FO4Edit v4.0.4b'
# Current patch (1.11)
  - name: 'CWPointLookoutFO4Patch.esl'
    clean:
      - crc: 0x8509D0A1
        util: 'FO4Edit v4.0.4b'
```
