### ISSUE TITLE
Update Aloot's Home Plate

### ISSUE THREAD

**Issue by Diskmaster** [loot/fallout4#468]
Version bumped to 2.3 in header.
Rebuilt previsibines to standards used in 0.59, also fixed the incorrect file reference with the main player bed's material file.
Plugin was also compacted and ESL tagged. Going to have a big warning about starting a new save to previous players.

Location is unchanged but planning to no longer include in main archive. Will update if the current person that's hosting the original wants to update or not.

English
```
  - name: 'AlootHomePlate.esp'
    clean:
      - crc: 0x0E11C3C1
        util: 'FO4Edit v4.0.4b'
```

Spanish
```
  - name: 'AlootHomePlate.esp'
    clean:
      - crc: 0x7CC799D2
        util: 'FO4Edit v4.0.4b'
```

Italian
```
  - name: 'AlootHomePlate.esp'
    clean:
      - crc: 0x62025A38
        util: 'FO4Edit v4.0.4b'
```
