### ISSUE TITLE
Update PRP-SS2

### ISSUE THREAD

**Issue by Diskmaster** [loot/fallout4#473]
Updated to 0.61 (based on 2.2.1)

New file: PRP-SS2-Fixes-Ch2.esp (Split from previous plugin file, masters were updated in kind.)

Cleaning data:

```yaml
  - name: 'PRP-SS2-Fixes.esp'
    clean:
      - crc: 0x2DE650B6
        util: 'FO4Edit v4.0.4b'
        
  - name: 'PRP-SS2-Fixes-Ch2.esp'
    clean:
      - crc: 0x13E667D9
        util: 'FO4Edit v4.0.4b'
        
  - name: 'PRP-SS2.esp'
    clean:
      - crc: 0x4338CDE6
        util: 'FO4Edit v4.0.4b'
```
