### ISSUE TITLE
Advised by NexusModerator - Tannin to open a Dialog

### ISSUE THREAD

**Issue by Thirdstorm** [loot/fallout4#84]
For multiple mods I either author or contribute on and significant issues with LOOT's handling of them in Load Orders.

**Comment by SuperSandro2000** [comment]
Which mods specifically? I am sure the load order can be corrected for them

**Comment by Thirdstorm** [comment]
**Start with the LO Discussion...**
Generally Gambit77 and I have helped well over a thousand people over the two years or so, be it 1on1, Comment posts and responses or guiding them to tools and based on extensive testing, our understanding of the Fallout Engine, and Testing in CK this guide uses the best structure for proper load order priority. [FO4 Load order and enhanced performance ](https://www.nexusmods.com/fallout4/mods/10844/?=10)
If you'd like specific examples I'm sure we can dig them up.


**Mod specific** (Author, Contributor or Curator of the following)

-[ArmorKeywords.ESM](https://www.nexusmods.com/fallout4/mods/6091?tab=posts) -Framework-
Having some issues with order, and Vortex keeps prioritizing older versions of the ESM over updates when installing.

-[Unique NPCs](https://www.nexusmods.com/fallout4/mods/21248?tab=posts&BH=1) -Overhaul-
Spent countless hours (I mean like over a hundred) helping people with Load orders, 9/10 have used LOOT as a base, and it's incorrectly sorted it 100% of the time.
I edit nearly ever human/ghoul NPC, and add 3,000 new NPC's. It should be below most other mods editing the same type(s) of NPCs. 
Performance wise, most people have the best results below all other NPC mods, above Outfit mods unless they Edit NPC records.

-[Unique NPCs - Creatures and Monsters of the Commonwealth](https://www.nexusmods.com/fallout4/mods/24357?tab=posts&BH=1) -Overhaul-
It edits every "monster", non-BiPed NPC in Fallout 4.
Should be near the bottom of the Load Order, below all other similar mods, and most if not all mods touching outfits and leveled lists effecting the same (If it touched the "Outfit" of a "Monster" NPC, it will conflict and "Creatures and Monsters" it should be below it)
Exceptions - SuperMutantRedux should be below it.

-[SuperMutant Redux](https://www.nexusmods.com/fallout4/mods/11853?tab=posts) -Overhaul-
Below most other Overhaul mods, Below "Creatures and Monsters"

-[Raider Overhaul](https://www.nexusmods.com/fallout4/mods/9103) -Overhaul-
With other NPC overhaul mods, Below or Above Unique NPC's depending on priority of the mod user.

-[Armorsmith Extended](https://www.nexusmods.com/fallout4/mods/2228) -Overhaul-
Should be below all other apparel mods that do not use it as a dependency.

**Comment by Ortham** [comment]
Advice like "It should be below most other mods editing the same type(s) of NPCs." is fine for humans, but it's not really specific enough for LOOT - how is LOOT supposed to know what you mean by "most" and "same type(s)"? How can we test that LOOT is sorting correctly?

It's more useful to identify specific plugins that LOOT isn't sorting correctly, e.g. "LOOT is sorting ArmorKeywords.esm after Foobar.esm, but it should be the other way around", as then metadata can be added to solve a specific problem, and we can check that those two plugins then get sorted correctly.

**Comment by Thirdstorm** [comment]
Tell me what data you need, and I'm sure we can assist.
If it's examples of load order issues, we can do that..

In FOMOD based installs you can set flags for the type of mod for the setup, can LOOT look for the flags listed inside them?

If so would/could it not assist in the management?

**Comment by pStyl3** [comment]
LOOT's current data regarding the above mentioned plugins (only the relevant parts) is as follows:
```yaml
  - name: 'ArmorKeywords.esm'
    msg:
      - <<: *obsolete
        condition: 'version("ArmorKeywords.esm", "8.51", <)
```
```yaml
  - name: 'Armorsmith Extended.esp'
    group: *itemsGroup
    after:
      - 'EAMR.esp'
    msg:
      - <<: *obsolete
        condition: 'version("Armorsmith Extended.esp", "4.6", <)'
      - <<: *versionXIncY
        subs:
          - 'Armorsmith Extended'
          - 'Armor and Weapon Keywords Community Resource (AWKCR)'
        condition: 'version("Armorsmith Extended.esp", "4.6", >=) and version("ArmorKeywords.esm", "8.5", <)'
```
```yaml
  - name: 'RaiderOverhaul.esp'
    group: *npcOverhaulsGroup
```
```yaml
  - name: 'Unique NPCs.esp'
    group: *npcOverhaulsGroup
    after:
      - 'RaiderOverhaul.esp'

  - name: 'Unique NPCs - Creatures and Monsters.esp'
    group: *npcOverhaulsGroup
    after:
      - 'RaiderOverhaul.esp'
      - 'Unique NPCs.esp'
```
```yaml
  - name: 'SuperMutantRedux.esp'
    group: *npcOverhaulsGroup
    after:
      - 'RaiderOverhaul.esp'
      - 'Unique NPCs - Creatures and Monsters.esp'
```

https://abload.de/img/fo4groupsxxkrz.png

@Thirdstorm It is, as @Ortham has said:
> It's more useful to identify specific plugins that LOOT isn't sorting correctly, e.g. "LOOT is sorting ArmorKeywords.esm after Foobar.esm, but it should be the other way around", as then metadata can be added to solve a specific problem, and we can check that those two plugins then get sorted correctly.

The information that `Plugin A` needs to load after `Overhaul mods` is something that LOOT can't understand like that. It is a generic statement that humans can understand, but in order for LOOT to sort plugins it must know the actual filenames; and therefore we need to know them, if we want to implement them into the masterlist.

> In FOMOD based installs you can set flags for the type of mod for the setup, can LOOT look for the flags listed inside them?

LOOT doesn't look up FOMODs. See [here](https://loot-api.readthedocs.io/en/latest/api/sorting.html) for more information on LOOT's sorting algorithm.

It's also always  a bit problematic if there is a statement to load a mod as follows:
> Other mods
> MyMod.esp

To say that a plugin needs to be at the bottom of the load order should always have specific reasons, other than that the plugin in question needs to win all conflicts just for the sake of it. LOOT's goal is to maximize the impact of each plugin on the game, so if no rules say otherswise, it loads bigger plugins early, and smaller plugins later, so that the smaller plugins have a greater chance to be meaningful.

This isn't to say, that we can't let plugins load later, we can. But knowing the actual reasoning behind it is always favorable.

So the question is, what is the situation for the plugins above with the quoted additions to the masterlist? Is there need for further adjustments? If so, what specific plugins would need to load different / below others, to make it work better?
