### ISSUE TITLE
FO4Edit Cleaning Reports

### ISSUE THREAD

**Issue by MacSplody** [loot/fallout4#98]
Submit Cleaning Reports as a comment below.
Make sure you **link** the mod page and specify the mod **version** you cleaned as well.

[Quick Auto Clean](https://tes5edit.github.io/docs/5-mod-cleaning-and-error-checking.html#quickautoclean)
[Add arguments](https://user-images.githubusercontent.com/1944639/48548367-b2744b00-e8c4-11e8-8a75-a0b67a4d7ed8.png)
`-iknowwhatimdoing -quickautoclean` in MO2
![image](https://user-images.githubusercontent.com/1944639/53291495-05a34700-37ac-11e9-9f01-58c1ef071b9e.png)
![image](https://user-images.githubusercontent.com/1944639/53291500-15229000-37ac-11e9-91ef-a8cd66b29fa2.png)

If you're using **Vortex**
![image](https://user-images.githubusercontent.com/1944639/53291485-f02e1d00-37ab-11e9-9782-fc857df4c34b.png)
![image](https://user-images.githubusercontent.com/1944639/53291491-f91eee80-37ab-11e9-8172-6d1e2b27a7b8.png)

[Copy the Quick Auto Clean report](https://user-images.githubusercontent.com/1944639/48547682-1eee4a80-e8c3-11e8-8e2b-fd0b571f71fc.png)

It's preferable to wrap this in a comment for readability.

![image](https://user-images.githubusercontent.com/1944639/48547617-fb2b0480-e8c2-11e8-969d-f7b698b05e05.png)
![image](https://user-images.githubusercontent.com/1944639/56073804-81c80d00-5da1-11e9-92b1-e791ee54830d.png)

```yaml
  - name: 'DLCCoast.esm'
    dirty:
      #  version: 1.10.120.0
      - <<: *quickClean
        crc: 0xF1F28026
        util: '[FO4Edit v4.0.0](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 85
        udr: 86
    clean:
      #  version: 1.10.120.0
      - crc: 0x4EB1FFA0
        util: 'FO4Edit v4.0.0'
```
Some plugins require a second PASS of Quick Auto Clean
Include all cleaning passes.
LOOT Masterlist Entries

```yaml
  - name: 'DLCworkshop03.esm'
    dirty:
      #  version: 1.10.120.0
      - <<: *quickClean
        crc: 0xE0089FBB
        util: '[FO4Edit v4.0.0](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 22
        udr: 10
      #  version: 1.10.120.0 - Before Second pass of Cleaning
      - <<: *quickClean
        crc: 0x09F6B3C8
        util: '[FO4Edit v4.0.0](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 3
    clean:
      # version: 1.10.120.0
      - crc: 0x41B1E1FE
        util: 'FO4Edit v4.0.0'
```
---

**Comment by MacSplody** [comment]
### [Diamond City Expansion](https://www.nexusmods.com/fallout4/mods/21853)

```yaml
  - name: 'Stm_DiamondCityExpansion.esp'
    dirty:
      #  version: 1.4.2 - Before Quick Clean
      - <<: *reqManualFix
        crc: 0xB3A2F88B
        util: '[FO4Edit v4.0.1](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 482
        udr: 6
        nav: 8
      #  version: 1.4.2 - After Quick Clean
      - <<: *reqManualFix
        crc: 0x5E45D526
        util: '[FO4Edit v4.0.1](https://www.nexusmods.com/fallout4/mods/2737)'
        nav: 8
```
Reported to Mod Author
![image](https://user-images.githubusercontent.com/1944639/53292774-ee6e5480-37bf-11e9-9148-5ab7fece69f3.png)

**Comment by MacSplody** [comment]
### [Minuteman Watchtowers](https://www.nexusmods.com/fallout4/mods/30363)

```yaml
  - name: 'Minuteman Watchtowers.esp'
    dirty:
      #  version: 0.1 - Before Quick Clean
      - <<: *quickClean
        crc: 0x4EAAA5D7
        util: '[FO4Edit v4.0.1](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 11
    clean:
      #  version: 0.1 - After Quick Clean
      - crc: 0x815F6E09
        util: 'FO4Edit v4.0.1'
```

**Comment by MacSplody** [comment]
### [Pipsy - Commonwealth Street Artist](https://www.nexusmods.com/fallout4/mods/34304)

```yaml
  - name: 'Pipsy.esp'
    dirty:
      #  version: 1.0 - Before Quick Clean
      - <<: *quickClean
        crc: 0xDF7D6406
        util: '[FO4Edit v4.0.1](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 121
        udr: 20
      #  version: 1.0 - Before 2nd Pass of Quick Clean
      - <<: *quickClean
        crc: 0xAFA33BE5
        util: '[FO4Edit v4.0.1](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 1
    clean:
      #  version: 1.0 - After Quick Clean
      - crc: 0xC4130107
        util: 'FO4Edit v4.0.1'

  - name: 'Pipsy.esl'
    dirty:
      #  version: 1.0 - Before Quick Clean
      - <<: *quickClean
        crc: 0x72261C69
        util: '[FO4Edit v4.0.1](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 131
        udr: 20
      #  version: 1.0 - Before 2nd Pass of Quick Clean
      - <<: *quickClean
        crc: 0x585FC8C4
        util: '[FO4Edit v4.0.1](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 1
    clean:
      #  version: 1.0 - After Quick Clean
      - crc: 0x3A94C02C
        util: 'FO4Edit v4.0.1'

```

Already Reported to Mod Author
![image](https://user-images.githubusercontent.com/1944639/53292763-c252d380-37bf-11e9-8877-38d3396a4dec.png)

**Comment by MacSplody** [comment]
### [Atomic Radio and Tales from the Commonwealth](https://www.nexusmods.com/fallout4/mods/8704)

```yaml
  - name: 'AtomicRadio.esp'
    clean:
      #  version: 2.6
      - crc: 0x3DED15D9
        util: 'FO4Edit v4.0.1'

  - name: '3DNPC_FO4.esp'
    dirty:
      #  version: 3.01
      - <<: *quickClean
        crc: 0xEC6C547B
        util: '[FO4Edit v4.0.1](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 31
    clean:
      #  version: 3.01
      - crc: 0x9F8C2A1B
        util: 'FO4Edit v4.0.1'

  - name: '3DNPC_FO4_DLC.esp'
    dirty:
      #  version: 2.5
      - <<: *quickClean
        crc: 0x2289431A
        util: '[FO4Edit v4.0.1](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 5
    clean:
      #  version: 2.5
      - crc: 0x9C2DC712
        util: 'FO4Edit v4.0.1'

  - name: '3DNPC_FO4Settler.esp'
    clean:
      #  version: 3.11
      - crc: 0x92ED5554
        util: 'FO4Edit v4.0.1'
```

### Notes
ITMs in `3DNPC_FO4_DLC.esp` are not major as it only references new formIDs added by `3DNPC_FO4.esp`.

##### xEDIT Delta Patch
_Shows Record Changes made by cleaning in xEdit._
[3DNPC_FO4_Quick_Clean_Results_ESU_(Delta Patch).zip](https://github.com/loot/fallout4/files/2897986/3DNPC_FO4_Quick_Clean_Results_ESU_.Delta.Patch.zip)

  ITMs removed from `3DNPC_FO4.esp`
<details>
<summary>Click to view</summary>
 
---

```
[01:22] Done: Applying Filter, [Pass 1] Processed Records: 90888, [Pass 2] Processed Records: 85296, Remaining unfiltered nodes: 85296, Elapsed Time: 01:06
[Undeleting and Disabling References done]  Processed Records: 85295, Undeleted Records: 0, Elapsed Time: 00:00
Removing: [NAVM:0011A933] (in GRUP Cell Temporary Children of DiamondCityExt01 [CELL:0000E50D] (in Commonwealth "Commonwealth" [WRLD:0000003C] at -5,-8))
Removing: [NAVM:00183114] (in GRUP Cell Temporary Children of [CELL:0000E509] (in Commonwealth "Commonwealth" [WRLD:0000003C] at -1,-8))
Removing: [NAVM:001FE335] (in GRUP Cell Temporary Children of [CELL:0000E4EA] (in Commonwealth "Commonwealth" [WRLD:0000003C] at -3,-7))
Removing: [NAVM:00227523] (in GRUP Cell Temporary Children of RoadsidePinesMotelExt03 [CELL:0000E582] (in Commonwealth "Commonwealth" [WRLD:0000003C] at -23,-11))
Removing: [NAVM:001D63A9] (in GRUP Cell Temporary Children of LakeCochituateExt04 [CELL:0000E57E] (in Commonwealth "Commonwealth" [WRLD:0000003C] at -19,-11))
Removing: [NAVM:001CCC21] (in GRUP Cell Temporary Children of RoadsidePinesMotelExt [CELL:0000E560] (in Commonwealth "Commonwealth" [WRLD:0000003C] at -22,-10))
Removing: [NAVM:00247E75] (in GRUP Cell Temporary Children of RoadsidePinesMotelExt [CELL:0000E560] (in Commonwealth "Commonwealth" [WRLD:0000003C] at -22,-10))
Removing: [NAVM:00217E0F] (in GRUP Cell Temporary Children of [CELL:00013CE5] (in Commonwealth "Commonwealth" [WRLD:0000003C] at -16,-33))
Removing: GRUP Cell Temporary Children of [CELL:00013CE5] (in Commonwealth "Commonwealth" [WRLD:0000003C] at -16,-33)
Removing: [CELL:00013CE5] (in Commonwealth "Commonwealth" [WRLD:0000003C] at -16,-33)
Removing: [NAVM:001BDB97] (in GRUP Cell Temporary Children of [CELL:0000DEBE] (in Commonwealth "Commonwealth" [WRLD:0000003C] at -7,10))
Removing: [NAVM:00125716] (in GRUP Cell Temporary Children of SuperDuperMartExt [CELL:0000DEC0] (in Commonwealth "Commonwealth" [WRLD:0000003C] at -9,10))
Removing: [NAVM:00184884] (in GRUP Cell Temporary Children of WaterfrontExtE [CELL:0000E0B3] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 8,-5))
Removing: [NAVM:00238D82] (in GRUP Cell Temporary Children of MassBayMedicalCenterExt [CELL:0000E0F5] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 4,-7))
Removing: [NAVM:00183135] (in GRUP Cell Temporary Children of BostonCommonExt02 [CELL:0000E0D8] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 2,-6))
Removing: [NAVM:001766E5] (in GRUP Cell Temporary Children of CombatZoneExt [CELL:0000E0D7] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 3,-6))
Removing: [NAVM:00187782] (in GRUP Cell Temporary Children of CombatZoneExt [CELL:0000E0D7] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 3,-6))
Removing: [NAVM:0024075C] (in GRUP Cell Temporary Children of CombatZoneExt [CELL:0000E0D7] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 3,-6))
Removing: [NAVM:0024858E] (in GRUP Cell Temporary Children of ShamrockTaphouseExt [CELL:0000E0B4] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 7,-5))
Removing: [NAVM:000984A6] (in GRUP Cell Temporary Children of Financial22Ext [CELL:0000E095] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 7,-4))
Removing: [NAVM:00237696] (in GRUP Cell Temporary Children of Financial22Ext [CELL:0000E095] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 7,-4))
Removing: [NAVM:001F1445] (in GRUP Cell Temporary Children of JamaicaPlainExt [CELL:0000E1EE] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 3,-15))
Removing: [NAVM:00216266] (in GRUP Cell Temporary Children of UniversityPointExt03 [CELL:0000E1CD] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 5,-14))
Removing: [NAVM:001A004E] (in GRUP Cell Temporary Children of NahantPDExt [CELL:0000DB54] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 20,6))
Removing: [NAVM:00209863] (in GRUP Cell Temporary Children of [CELL:0000DB36] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 19,7))
Removing: [NAVM:002306AD] (in GRUP Cell Temporary Children of EasyCityDownsExt [CELL:0000DBB9] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 12,3))
Removing: DmndScienceCenter01 "Science! Center" [CELL:00001E57]
Removing: GoodneighborTheMemoryDen "The Memory Den" [CELL:00022884]
Removing: GRUP Interior Cell Sub-Block 4
Removing: RailroadHQEscapeTunnel "Railroad HQ Escape Tunnel" [CELL:00137C87]
Removing: GRUP Interior Cell Sub-Block 6
[Removing "Identical to Master" records done]  Processed Records: 85295, Removed Records: 31, Elapsed Time: 00:00
```

  ---
</details>

**Comment by MacSplody** [comment]
### [The Beantown interiors Project](https://www.nexusmods.com/fallout4/mods/4612)

```yaml
  - name: 'BTInteriors_Project.esp'
    dirty:
      - <<: *quickClean
        crc: 0xD66FE314
        util: '[FO4Edit v4.0.1](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 43
    clean:
      - crc: 0x443BA348
        util: 'FO4Edit v4.0.1'
```

### Notes
##### xEDIT Delta Patch
_Shows Record Changes made by cleaning in xEdit._
[BTInteriors_Project_Quick_Clean_Diff.zip](https://github.com/loot/fallout4/files/2898484/BTInteriors_Project_Quick_Clean_Diff.zip)


  ITMs removed from `BTInteriors_Project.esp`
<details>
<summary>Click to view</summary>
 
---

```
[02:03] Done: Applying Filter, [Pass 1] Processed Records: 28602, [Pass 2] Processed Records: 28273, Remaining unfiltered nodes: 28273, Elapsed Time: 01:39
[Undeleting and Disabling References done]  Processed Records: 28272, Undeleted Records: 0, Elapsed Time: 00:00
Removing: [NAVM:02039719] (in GRUP Cell Temporary Children of [CELL:0200315C] (in NukaWorld "Nuka-World" [WRLD:0200290F] at 0,-11))
Removing: [NAVM:0203971D] (in GRUP Cell Temporary Children of [CELL:0200311C] (in NukaWorld "Nuka-World" [WRLD:0200290F] at 1,-12))
Removing: [NAVM:0203BA10] (in GRUP Cell Temporary Children of DLC04POIRJ03 [CELL:0200311B] (in NukaWorld "Nuka-World" [WRLD:0200290F] at 1,-11))
Removing: [NAVM:02039722] (in GRUP Cell Temporary Children of [CELL:0200311A] (in NukaWorld "Nuka-World" [WRLD:0200290F] at 1,-10))
Removing: [NAVM:02039721] (in GRUP Cell Temporary Children of [CELL:020030DA] (in NukaWorld "Nuka-World" [WRLD:0200290F] at 2,-11))
Removing: [NAVM:0203F912] (in GRUP Cell Temporary Children of DLC04POIBB05 [CELL:02003001] (in NukaWorld "Nuka-World" [WRLD:0200290F] at 5,11))
Removing: [NAVM:02051992] (in GRUP Cell Temporary Children of BradbertonExt05 [CELL:02002FC1] (in NukaWorld "Nuka-World" [WRLD:0200290F] at 6,10))
Removing: [NAVM:02042EF8] (in GRUP Cell Temporary Children of BradbertonExt02 [CELL:02002FC0] (in NukaWorld "Nuka-World" [WRLD:0200290F] at 6,11))
Removing: [NAVM:02056756] (in GRUP Cell Temporary Children of BradbertonExt [CELL:02002F7F] (in NukaWorld "Nuka-World" [WRLD:0200290F] at 7,11))
Removing: [LAND:0100134D]
Removing: [NAVM:0021086D] (in GRUP Cell Temporary Children of [CELL:0000D9BC] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 24,19))
Removing: [NAVM:000DAEEF] (in GRUP Cell Temporary Children of [CELL:0000DB31] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 24,7))
Removing: [NAVM:002496D4] (in GRUP Cell Temporary Children of BarneysBunkerExt04 [CELL:0000D97F] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 23,21))
Removing: [LAND:0000F4C7]
Removing: GRUP Cell Temporary Children of EastBostonPrepSchoolExt02 [CELL:0000DBBA] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 11,3)
Removing: EastBostonPrepSchoolExt02 [CELL:0000DBBA] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 11,3)
Removing: [NAVM:002306AD] (in GRUP Cell Temporary Children of EasyCityDownsExt [CELL:0000DBB9] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 12,3))
Removing: [LAND:0000F4E7]
Removing: [NAVM:00222C57] (in GRUP Cell Temporary Children of [CELL:0000DAA9] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 4,12))
Removing: [NAVM:001CCFC2] (in GRUP Cell Temporary Children of [CELL:0000DF9E] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 0,3))
Removing: [NAVM:0023F631] (in GRUP Cell Temporary Children of CambridgeConstructionSiteExt02 [CELL:0000DBC3] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 1,3))
Removing: [NAVM:001291E5] (in GRUP Cell Temporary Children of [CELL:0000E2A3] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 8,-21))
Removing: [NAVM:001B8806] (in GRUP Cell Temporary Children of [CELL:0000E2A3] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 8,-21))
Removing: [NAVM:0024954D] (in GRUP Cell Temporary Children of JamaicaPlainExt05 [CELL:0000E20E] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 2,-16))
Removing: [LAND:0000EE92]
Removing: [LAND:0000EE93]
Removing: [NAVM:00216266] (in GRUP Cell Temporary Children of UniversityPointExt03 [CELL:0000E1CD] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 5,-14))
Removing: [NAVM:00245945] (in GRUP Cell Temporary Children of HydeParkExt06 [CELL:0000E673] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 0,-19))
Removing: [NAVM:00245CC4] (in GRUP Cell Temporary Children of QuincyRuinsExt06 [CELL:0000E2E3] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 6,-23))
Removing: [LAND:0000EDBC]
Removing: [NAVM:001291E1] (in GRUP Cell Temporary Children of QuincyRuinsExt05 [CELL:0000E2C3] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 7,-22))
Removing: [NAVM:001291E2] (in GRUP Cell Temporary Children of QuincyRuinsExt05 [CELL:0000E2C3] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 7,-22))
Removing: [NAVM:001291E3] (in GRUP Cell Temporary Children of QuincyRuinsExt05 [CELL:0000E2C3] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 7,-22))
Removing: [NAVM:0008B579] (in GRUP Cell Temporary Children of QuincyRuinsExt02 [CELL:0000E2A5] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 6,-21))
Removing: [NAVM:0012583D] (in GRUP Cell Temporary Children of QuincyRuinsExt03 [CELL:0000E2A4] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 7,-21))
Removing: [NAVM:00249548] (in GRUP Cell Temporary Children of JamaicaPlainExt08 [CELL:0000E22D] (in Commonwealth "Commonwealth" [WRLD:0000003C] at 2,-17))
Removing: [NAVM:001F929B] (in GRUP Cell Temporary Children of LexingtonExt04 [CELL:0000DEE0] (in Commonwealth "Commonwealth" [WRLD:0000003C] at -8,9))
Removing: [LAND:0000F0C0]
Removing: [LAND:0000F0C1]
Removing: [LAND:0000F0E0]
Removing: [NAVM:0017E140] (in GRUP Cell Temporary Children of [CELL:0000DF7F] (in Commonwealth "Commonwealth" [WRLD:0000003C] at -2,4))
Removing: [NAVM:0001D238] (in GRUP Cell Temporary Children of ConcordMuseumExt02 [CELL:0000DDFF] (in Commonwealth "Commonwealth" [WRLD:0000003C] at -14,16))
Removing: [NAVM:00210872] (in GRUP Cell Temporary Children of MQ106TrackingSite04 [CELL:0000E4D7] (in Commonwealth "Commonwealth" [WRLD:0000003C] at -17,-6))
[Removing "Identical to Master" records done]  Processed Records: 28272, Removed Records: 43, Elapsed Time: 00:00
```

  ---
</details>

**Comment by MacSplody** [comment]
Reported on Discord by `Chef#1579` https://discordapp.com/channels/473542112974077963/473542230095822848/564537803199873025

[South of The Sea](https://www.nexusmods.com/fallout4/mods/27870)
Version: 0.60
```yaml
  - name: 'SOTS.esp'
    url: [ 'https://www.nexusmods.com/fallout4/mods/27870' ]
    dirty:
      - <<: *reqManualFix
        crc: 0x7AED0F0B
        util: '[FO4Edit v4.0.2](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 12
        udr: 119
        nav: 41
      - <<: *reqManualFix
        crc: 0x407CEB41
        util: '[FO4Edit v4.0.2](https://www.nexusmods.com/fallout4/mods/2737)'
        nav: 41
```

**Comment by MacSplody** [comment]
Reported on Discord by Chef#1579 https://discordapp.com/channels/473542112974077963/473542230095822848/565978474808868934

[Fallout 4 Northern Springs DLC](https://www.nexusmods.com/fallout4/mods/32911)
Version: Beta-1B
```yaml
  - name: 'JonsMod.esm'
    dirty:
      - <<: *reqManualFix
        crc: 0x2BEB494C
        util: '[FO4Edit v4.0.2](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 131
        nav: 9
      - <<: *reqManualFix
        crc: 0x4C7A2C75
        util: '[FO4Edit v4.0.2](https://www.nexusmods.com/fallout4/mods/2737)'
        nav: 9
```

**Comment by Chef0000** [comment]
[https://www.nexusmods.com/fallout4/mods/12490?tab=files](url)
```yaml

  - name: 'BobbleMagazine.esp'
    dirty:
      - <<: *quickClean
        crc: 0x0C35F87A
        util: '[FO4Edit v4.0.2](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 5
        udr: 138
    dirty:
      - <<: *quickClean
        crc: 0xD18AB395
        util: '[FO4Edit v4.0.2](https://www.nexusmods.com/fallout4/mods/2737)'
        itm: 1
    clean:
      - crc: 0x2AB3FC7F
        util: 'FO4Edit v4.0.2'
```

**Comment by Chef0000** [comment]
[Rad-Ban Eyewear Inc.](https://www.nexusmods.com/fallout4/mods/8342)

```
 - name: 'NukaRadBans.esp'
    [ 'https://www.nexusmods.com/fallout4/mods/8342']
    dirty:
      - <<: *quickClean
        crc: 0x174F8132
        util: '[FO4Edit v4.0.2](https://www.nexusmods.com/fallout4/mods/2737)'
        udr: 1
    clean:
      - crc: 0x93572428
        util: 'FO4Edit v4.0.2'
```
